branch-defaults:
  develop:
    environment: bbs2-dev
global:
  application_name: bbs2
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.03 v1.4.3 running Ruby 2.2 (Puma)
  default_region: ap-northeast-1
  sc: git
